name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm run build --if-present
      - name: Run BundleMon
        run: npm run bundlemon
        env:
          BUNDLEMON_PROJECT_ID: 62325f451d1b50bea48f41fb
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}} # important!
      # Keeping in case we ever want to save build artifacts
      # - name: Zip artifact
      #   run: zip build-artifact -r ./build ./node_modules
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: build-artifact
      #     path: ./build-artifact.zip
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm test
        env:
          CI: true

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  coverage-cypress:
    env:
      REACT_APP_NOTIFY_DAPP_ID: ${{ secrets.REACT_APP_NOTIFY_DAPP_ID }}
    runs-on: ubuntu-latest
    services:
      saddle-contract:
        image: saddlefinance/contracts:latest
        options: >-
          --health-cmd "node -e 'const fetch=require(\"node-fetch\");(function main(){const body={method:\"eth_blockNumber\",params:[],id:1,jsonrpc:\"2.0\"};fetch(\"http://localhost:8545\",{method:\"POST\",body:JSON.stringify(body),headers:{\"Content-Type\":\"application/json\"}}).then((res)=>res.json()).then((json)=>{const block=parseInt(json.result||\"0x0\",16);if(block>0){process.exit(0)}throw new Error()}).catch(()=>process.exit(1))})();'"
          --health-interval 20s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8545:8545
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm run cy:coverage
        env:
          CHOKIDAR_USEPOLLING: 1
      - run: npx nyc report --reporter=text
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: E2E Failures
          path: cypress/screenshots/
